### ISSUE TITLE
Iconen toevoegen aan de stekjes

### ISSUE THREAD

**Issue by joelle78** [TimOosterveer/plantswap-webapplicatie#1]
de stekjes en de stekjes detailpagina hebben iconen nodig.

**Comment by iBadr49** [comment]
![Image](https://github.com/TimOosterveer/plantswap-webapplicatie/assets/112857932/17b7d0fd-0c92-43c7-ac7a-8b0231a60cd7)

**Comment by milanrolie** [comment]
Misschien als het niet teveel werk is de iconen dezelfde kleur maken als de tekst.

**Comment by iBadr49** [comment]
- Ik vind zwart veel beter, je kan iconen onderscheiden van de tekst!

![Image](https://github.com/TimOosterveer/plantswap-webapplicatie/assets/112857932/7c8b4f46-6fb4-47c5-8f8b-b11f86bd18b7)
