### ISSUE TITLE
Kopje "Beschrijving" detail-page niet consistent

### ISSUE THREAD

**Issue by TimOosterveer** [TimOosterveer/plantswap-webapplicatie#30]
Heading "Beschrijving" niet groot genoeg!

<img width="373" alt="image" src="https://github.com/TimOosterveer/plantswap-webapplicatie/assets/62908209/a8905c04-a77d-4a58-822b-59c3890c9684">

**Comment by iBadr49** [comment]
- Gefixt

> ![Image](https://github.com/TimOosterveer/plantswap-webapplicatie/assets/112857932/514bd893-6f6f-4762-9493-5a157657e1c9)
