### ISSUE TITLE
Container stekjes cards staat nu in het midden

### ISSUE THREAD

**Issue by TimOosterveer** [TimOosterveer/plantswap-webapplicatie#37]
Deze kaartjes staan nu in het midden, neem aan dat hier een media query voor geschreven moet worden!? 

![image](https://github.com/TimOosterveer/plantswap-webapplicatie/assets/62908209/709231ad-9987-4540-93d9-1f381bf51fd4)

**Comment by YoussraElmortai** [comment]
is gefixt
